// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TArticleColumns holds the columns for the "t_article" table.
	TArticleColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "origin_name", Type: field.TypeString},
		{Name: "origin_type", Type: field.TypeString},
		{Name: "url", Type: field.TypeString, Unique: true},
		{Name: "title", Type: field.TypeString},
		{Name: "title_chinese", Type: field.TypeString, Nullable: true},
		{Name: "author", Type: field.TypeString, Nullable: true},
		{Name: "published_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "raw", Type: field.TypeString, Size: 2147483647},
		{Name: "crawled_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP", SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "summary_chinese", Type: field.TypeString, Nullable: true, Size: 2147483647},
	}
	// TArticleTable holds the schema information for the "t_article" table.
	TArticleTable = &schema.Table{
		Name:       "t_article",
		Columns:    TArticleColumns,
		PrimaryKey: []*schema.Column{TArticleColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "article_title",
				Unique:  false,
				Columns: []*schema.Column{TArticleColumns[4]},
			},
			{
				Name:    "article_title_chinese",
				Unique:  false,
				Columns: []*schema.Column{TArticleColumns[5]},
			},
			{
				Name:    "article_origin_name",
				Unique:  false,
				Columns: []*schema.Column{TArticleColumns[1]},
			},
			{
				Name:    "article_origin_type",
				Unique:  false,
				Columns: []*schema.Column{TArticleColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TArticleTable,
	}
)

func init() {
	TArticleTable.Annotation = &entsql.Annotation{
		Table:     "t_article",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_general_ci",
	}
}
