// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/wolodata/schema/ent/article"
	"github.com/wolodata/schema/ent/predicate"
	"github.com/wolodata/schema/ent/schema"
)

// ArticleUpdate is the builder for updating Article entities.
type ArticleUpdate struct {
	config
	hooks    []Hook
	mutation *ArticleMutation
}

// Where appends a list predicates to the ArticleUpdate builder.
func (au *ArticleUpdate) Where(ps ...predicate.Article) *ArticleUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetTitleChinese sets the "title_chinese" field.
func (au *ArticleUpdate) SetTitleChinese(s string) *ArticleUpdate {
	au.mutation.SetTitleChinese(s)
	return au
}

// SetNillableTitleChinese sets the "title_chinese" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableTitleChinese(s *string) *ArticleUpdate {
	if s != nil {
		au.SetTitleChinese(*s)
	}
	return au
}

// SetTitleEnglish sets the "title_english" field.
func (au *ArticleUpdate) SetTitleEnglish(s string) *ArticleUpdate {
	au.mutation.SetTitleEnglish(s)
	return au
}

// SetNillableTitleEnglish sets the "title_english" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableTitleEnglish(s *string) *ArticleUpdate {
	if s != nil {
		au.SetTitleEnglish(*s)
	}
	return au
}

// SetAuthor sets the "author" field.
func (au *ArticleUpdate) SetAuthor(s []string) *ArticleUpdate {
	au.mutation.SetAuthor(s)
	return au
}

// AppendAuthor appends s to the "author" field.
func (au *ArticleUpdate) AppendAuthor(s []string) *ArticleUpdate {
	au.mutation.AppendAuthor(s)
	return au
}

// SetHTMLChinese sets the "html_chinese" field.
func (au *ArticleUpdate) SetHTMLChinese(s string) *ArticleUpdate {
	au.mutation.SetHTMLChinese(s)
	return au
}

// SetNillableHTMLChinese sets the "html_chinese" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableHTMLChinese(s *string) *ArticleUpdate {
	if s != nil {
		au.SetHTMLChinese(*s)
	}
	return au
}

// SetHTMLEnglish sets the "html_english" field.
func (au *ArticleUpdate) SetHTMLEnglish(s string) *ArticleUpdate {
	au.mutation.SetHTMLEnglish(s)
	return au
}

// SetNillableHTMLEnglish sets the "html_english" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableHTMLEnglish(s *string) *ArticleUpdate {
	if s != nil {
		au.SetHTMLEnglish(*s)
	}
	return au
}

// SetTextChinese sets the "text_chinese" field.
func (au *ArticleUpdate) SetTextChinese(s string) *ArticleUpdate {
	au.mutation.SetTextChinese(s)
	return au
}

// SetNillableTextChinese sets the "text_chinese" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableTextChinese(s *string) *ArticleUpdate {
	if s != nil {
		au.SetTextChinese(*s)
	}
	return au
}

// SetTextEnglish sets the "text_english" field.
func (au *ArticleUpdate) SetTextEnglish(s string) *ArticleUpdate {
	au.mutation.SetTextEnglish(s)
	return au
}

// SetNillableTextEnglish sets the "text_english" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableTextEnglish(s *string) *ArticleUpdate {
	if s != nil {
		au.SetTextEnglish(*s)
	}
	return au
}

// SetImages sets the "images" field.
func (au *ArticleUpdate) SetImages(s []string) *ArticleUpdate {
	au.mutation.SetImages(s)
	return au
}

// AppendImages appends s to the "images" field.
func (au *ArticleUpdate) AppendImages(s []string) *ArticleUpdate {
	au.mutation.AppendImages(s)
	return au
}

// SetWeakProcessed sets the "weak_processed" field.
func (au *ArticleUpdate) SetWeakProcessed(b bool) *ArticleUpdate {
	au.mutation.SetWeakProcessed(b)
	return au
}

// SetNillableWeakProcessed sets the "weak_processed" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableWeakProcessed(b *bool) *ArticleUpdate {
	if b != nil {
		au.SetWeakProcessed(*b)
	}
	return au
}

// SetWeakRelated sets the "weak_related" field.
func (au *ArticleUpdate) SetWeakRelated(b bool) *ArticleUpdate {
	au.mutation.SetWeakRelated(b)
	return au
}

// SetNillableWeakRelated sets the "weak_related" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableWeakRelated(b *bool) *ArticleUpdate {
	if b != nil {
		au.SetWeakRelated(*b)
	}
	return au
}

// SetWeakKeywords sets the "weak_keywords" field.
func (au *ArticleUpdate) SetWeakKeywords(sk []schema.WeakKeyword) *ArticleUpdate {
	au.mutation.SetWeakKeywords(sk)
	return au
}

// AppendWeakKeywords appends sk to the "weak_keywords" field.
func (au *ArticleUpdate) AppendWeakKeywords(sk []schema.WeakKeyword) *ArticleUpdate {
	au.mutation.AppendWeakKeywords(sk)
	return au
}

// SetStrongProcessed sets the "strong_processed" field.
func (au *ArticleUpdate) SetStrongProcessed(b bool) *ArticleUpdate {
	au.mutation.SetStrongProcessed(b)
	return au
}

// SetNillableStrongProcessed sets the "strong_processed" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableStrongProcessed(b *bool) *ArticleUpdate {
	if b != nil {
		au.SetStrongProcessed(*b)
	}
	return au
}

// SetStrongRelated sets the "strong_related" field.
func (au *ArticleUpdate) SetStrongRelated(b bool) *ArticleUpdate {
	au.mutation.SetStrongRelated(b)
	return au
}

// SetNillableStrongRelated sets the "strong_related" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableStrongRelated(b *bool) *ArticleUpdate {
	if b != nil {
		au.SetStrongRelated(*b)
	}
	return au
}

// SetStrongKeyword sets the "strong_keyword" field.
func (au *ArticleUpdate) SetStrongKeyword(sk schema.StrongKeyword) *ArticleUpdate {
	au.mutation.SetStrongKeyword(sk)
	return au
}

// SetNillableStrongKeyword sets the "strong_keyword" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableStrongKeyword(sk *schema.StrongKeyword) *ArticleUpdate {
	if sk != nil {
		au.SetStrongKeyword(*sk)
	}
	return au
}

// ClearStrongKeyword clears the value of the "strong_keyword" field.
func (au *ArticleUpdate) ClearStrongKeyword() *ArticleUpdate {
	au.mutation.ClearStrongKeyword()
	return au
}

// SetStrongRelatedCategory sets the "strong_related_category" field.
func (au *ArticleUpdate) SetStrongRelatedCategory(s string) *ArticleUpdate {
	au.mutation.SetStrongRelatedCategory(s)
	return au
}

// SetNillableStrongRelatedCategory sets the "strong_related_category" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableStrongRelatedCategory(s *string) *ArticleUpdate {
	if s != nil {
		au.SetStrongRelatedCategory(*s)
	}
	return au
}

// SetSummaryChinese sets the "summary_chinese" field.
func (au *ArticleUpdate) SetSummaryChinese(s string) *ArticleUpdate {
	au.mutation.SetSummaryChinese(s)
	return au
}

// SetNillableSummaryChinese sets the "summary_chinese" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableSummaryChinese(s *string) *ArticleUpdate {
	if s != nil {
		au.SetSummaryChinese(*s)
	}
	return au
}

// SetImageUploaded sets the "image_uploaded" field.
func (au *ArticleUpdate) SetImageUploaded(b bool) *ArticleUpdate {
	au.mutation.SetImageUploaded(b)
	return au
}

// SetNillableImageUploaded sets the "image_uploaded" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableImageUploaded(b *bool) *ArticleUpdate {
	if b != nil {
		au.SetImageUploaded(*b)
	}
	return au
}

// Mutation returns the ArticleMutation object of the builder.
func (au *ArticleUpdate) Mutation() *ArticleMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *ArticleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *ArticleUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *ArticleUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *ArticleUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

func (au *ArticleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(article.Table, article.Columns, sqlgraph.NewFieldSpec(article.FieldID, field.TypeString))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.TitleChinese(); ok {
		_spec.SetField(article.FieldTitleChinese, field.TypeString, value)
	}
	if value, ok := au.mutation.TitleEnglish(); ok {
		_spec.SetField(article.FieldTitleEnglish, field.TypeString, value)
	}
	if value, ok := au.mutation.Author(); ok {
		_spec.SetField(article.FieldAuthor, field.TypeJSON, value)
	}
	if value, ok := au.mutation.AppendedAuthor(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, article.FieldAuthor, value)
		})
	}
	if value, ok := au.mutation.HTMLChinese(); ok {
		_spec.SetField(article.FieldHTMLChinese, field.TypeString, value)
	}
	if value, ok := au.mutation.HTMLEnglish(); ok {
		_spec.SetField(article.FieldHTMLEnglish, field.TypeString, value)
	}
	if value, ok := au.mutation.TextChinese(); ok {
		_spec.SetField(article.FieldTextChinese, field.TypeString, value)
	}
	if value, ok := au.mutation.TextEnglish(); ok {
		_spec.SetField(article.FieldTextEnglish, field.TypeString, value)
	}
	if value, ok := au.mutation.Images(); ok {
		_spec.SetField(article.FieldImages, field.TypeJSON, value)
	}
	if value, ok := au.mutation.AppendedImages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, article.FieldImages, value)
		})
	}
	if value, ok := au.mutation.WeakProcessed(); ok {
		_spec.SetField(article.FieldWeakProcessed, field.TypeBool, value)
	}
	if value, ok := au.mutation.WeakRelated(); ok {
		_spec.SetField(article.FieldWeakRelated, field.TypeBool, value)
	}
	if value, ok := au.mutation.WeakKeywords(); ok {
		_spec.SetField(article.FieldWeakKeywords, field.TypeJSON, value)
	}
	if value, ok := au.mutation.AppendedWeakKeywords(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, article.FieldWeakKeywords, value)
		})
	}
	if value, ok := au.mutation.StrongProcessed(); ok {
		_spec.SetField(article.FieldStrongProcessed, field.TypeBool, value)
	}
	if value, ok := au.mutation.StrongRelated(); ok {
		_spec.SetField(article.FieldStrongRelated, field.TypeBool, value)
	}
	if value, ok := au.mutation.StrongKeyword(); ok {
		_spec.SetField(article.FieldStrongKeyword, field.TypeJSON, value)
	}
	if au.mutation.StrongKeywordCleared() {
		_spec.ClearField(article.FieldStrongKeyword, field.TypeJSON)
	}
	if value, ok := au.mutation.StrongRelatedCategory(); ok {
		_spec.SetField(article.FieldStrongRelatedCategory, field.TypeString, value)
	}
	if value, ok := au.mutation.SummaryChinese(); ok {
		_spec.SetField(article.FieldSummaryChinese, field.TypeString, value)
	}
	if value, ok := au.mutation.ImageUploaded(); ok {
		_spec.SetField(article.FieldImageUploaded, field.TypeBool, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{article.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// ArticleUpdateOne is the builder for updating a single Article entity.
type ArticleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ArticleMutation
}

// SetTitleChinese sets the "title_chinese" field.
func (auo *ArticleUpdateOne) SetTitleChinese(s string) *ArticleUpdateOne {
	auo.mutation.SetTitleChinese(s)
	return auo
}

// SetNillableTitleChinese sets the "title_chinese" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableTitleChinese(s *string) *ArticleUpdateOne {
	if s != nil {
		auo.SetTitleChinese(*s)
	}
	return auo
}

// SetTitleEnglish sets the "title_english" field.
func (auo *ArticleUpdateOne) SetTitleEnglish(s string) *ArticleUpdateOne {
	auo.mutation.SetTitleEnglish(s)
	return auo
}

// SetNillableTitleEnglish sets the "title_english" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableTitleEnglish(s *string) *ArticleUpdateOne {
	if s != nil {
		auo.SetTitleEnglish(*s)
	}
	return auo
}

// SetAuthor sets the "author" field.
func (auo *ArticleUpdateOne) SetAuthor(s []string) *ArticleUpdateOne {
	auo.mutation.SetAuthor(s)
	return auo
}

// AppendAuthor appends s to the "author" field.
func (auo *ArticleUpdateOne) AppendAuthor(s []string) *ArticleUpdateOne {
	auo.mutation.AppendAuthor(s)
	return auo
}

// SetHTMLChinese sets the "html_chinese" field.
func (auo *ArticleUpdateOne) SetHTMLChinese(s string) *ArticleUpdateOne {
	auo.mutation.SetHTMLChinese(s)
	return auo
}

// SetNillableHTMLChinese sets the "html_chinese" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableHTMLChinese(s *string) *ArticleUpdateOne {
	if s != nil {
		auo.SetHTMLChinese(*s)
	}
	return auo
}

// SetHTMLEnglish sets the "html_english" field.
func (auo *ArticleUpdateOne) SetHTMLEnglish(s string) *ArticleUpdateOne {
	auo.mutation.SetHTMLEnglish(s)
	return auo
}

// SetNillableHTMLEnglish sets the "html_english" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableHTMLEnglish(s *string) *ArticleUpdateOne {
	if s != nil {
		auo.SetHTMLEnglish(*s)
	}
	return auo
}

// SetTextChinese sets the "text_chinese" field.
func (auo *ArticleUpdateOne) SetTextChinese(s string) *ArticleUpdateOne {
	auo.mutation.SetTextChinese(s)
	return auo
}

// SetNillableTextChinese sets the "text_chinese" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableTextChinese(s *string) *ArticleUpdateOne {
	if s != nil {
		auo.SetTextChinese(*s)
	}
	return auo
}

// SetTextEnglish sets the "text_english" field.
func (auo *ArticleUpdateOne) SetTextEnglish(s string) *ArticleUpdateOne {
	auo.mutation.SetTextEnglish(s)
	return auo
}

// SetNillableTextEnglish sets the "text_english" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableTextEnglish(s *string) *ArticleUpdateOne {
	if s != nil {
		auo.SetTextEnglish(*s)
	}
	return auo
}

// SetImages sets the "images" field.
func (auo *ArticleUpdateOne) SetImages(s []string) *ArticleUpdateOne {
	auo.mutation.SetImages(s)
	return auo
}

// AppendImages appends s to the "images" field.
func (auo *ArticleUpdateOne) AppendImages(s []string) *ArticleUpdateOne {
	auo.mutation.AppendImages(s)
	return auo
}

// SetWeakProcessed sets the "weak_processed" field.
func (auo *ArticleUpdateOne) SetWeakProcessed(b bool) *ArticleUpdateOne {
	auo.mutation.SetWeakProcessed(b)
	return auo
}

// SetNillableWeakProcessed sets the "weak_processed" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableWeakProcessed(b *bool) *ArticleUpdateOne {
	if b != nil {
		auo.SetWeakProcessed(*b)
	}
	return auo
}

// SetWeakRelated sets the "weak_related" field.
func (auo *ArticleUpdateOne) SetWeakRelated(b bool) *ArticleUpdateOne {
	auo.mutation.SetWeakRelated(b)
	return auo
}

// SetNillableWeakRelated sets the "weak_related" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableWeakRelated(b *bool) *ArticleUpdateOne {
	if b != nil {
		auo.SetWeakRelated(*b)
	}
	return auo
}

// SetWeakKeywords sets the "weak_keywords" field.
func (auo *ArticleUpdateOne) SetWeakKeywords(sk []schema.WeakKeyword) *ArticleUpdateOne {
	auo.mutation.SetWeakKeywords(sk)
	return auo
}

// AppendWeakKeywords appends sk to the "weak_keywords" field.
func (auo *ArticleUpdateOne) AppendWeakKeywords(sk []schema.WeakKeyword) *ArticleUpdateOne {
	auo.mutation.AppendWeakKeywords(sk)
	return auo
}

// SetStrongProcessed sets the "strong_processed" field.
func (auo *ArticleUpdateOne) SetStrongProcessed(b bool) *ArticleUpdateOne {
	auo.mutation.SetStrongProcessed(b)
	return auo
}

// SetNillableStrongProcessed sets the "strong_processed" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableStrongProcessed(b *bool) *ArticleUpdateOne {
	if b != nil {
		auo.SetStrongProcessed(*b)
	}
	return auo
}

// SetStrongRelated sets the "strong_related" field.
func (auo *ArticleUpdateOne) SetStrongRelated(b bool) *ArticleUpdateOne {
	auo.mutation.SetStrongRelated(b)
	return auo
}

// SetNillableStrongRelated sets the "strong_related" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableStrongRelated(b *bool) *ArticleUpdateOne {
	if b != nil {
		auo.SetStrongRelated(*b)
	}
	return auo
}

// SetStrongKeyword sets the "strong_keyword" field.
func (auo *ArticleUpdateOne) SetStrongKeyword(sk schema.StrongKeyword) *ArticleUpdateOne {
	auo.mutation.SetStrongKeyword(sk)
	return auo
}

// SetNillableStrongKeyword sets the "strong_keyword" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableStrongKeyword(sk *schema.StrongKeyword) *ArticleUpdateOne {
	if sk != nil {
		auo.SetStrongKeyword(*sk)
	}
	return auo
}

// ClearStrongKeyword clears the value of the "strong_keyword" field.
func (auo *ArticleUpdateOne) ClearStrongKeyword() *ArticleUpdateOne {
	auo.mutation.ClearStrongKeyword()
	return auo
}

// SetStrongRelatedCategory sets the "strong_related_category" field.
func (auo *ArticleUpdateOne) SetStrongRelatedCategory(s string) *ArticleUpdateOne {
	auo.mutation.SetStrongRelatedCategory(s)
	return auo
}

// SetNillableStrongRelatedCategory sets the "strong_related_category" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableStrongRelatedCategory(s *string) *ArticleUpdateOne {
	if s != nil {
		auo.SetStrongRelatedCategory(*s)
	}
	return auo
}

// SetSummaryChinese sets the "summary_chinese" field.
func (auo *ArticleUpdateOne) SetSummaryChinese(s string) *ArticleUpdateOne {
	auo.mutation.SetSummaryChinese(s)
	return auo
}

// SetNillableSummaryChinese sets the "summary_chinese" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableSummaryChinese(s *string) *ArticleUpdateOne {
	if s != nil {
		auo.SetSummaryChinese(*s)
	}
	return auo
}

// SetImageUploaded sets the "image_uploaded" field.
func (auo *ArticleUpdateOne) SetImageUploaded(b bool) *ArticleUpdateOne {
	auo.mutation.SetImageUploaded(b)
	return auo
}

// SetNillableImageUploaded sets the "image_uploaded" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableImageUploaded(b *bool) *ArticleUpdateOne {
	if b != nil {
		auo.SetImageUploaded(*b)
	}
	return auo
}

// Mutation returns the ArticleMutation object of the builder.
func (auo *ArticleUpdateOne) Mutation() *ArticleMutation {
	return auo.mutation
}

// Where appends a list predicates to the ArticleUpdate builder.
func (auo *ArticleUpdateOne) Where(ps ...predicate.Article) *ArticleUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *ArticleUpdateOne) Select(field string, fields ...string) *ArticleUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Article entity.
func (auo *ArticleUpdateOne) Save(ctx context.Context) (*Article, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *ArticleUpdateOne) SaveX(ctx context.Context) *Article {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *ArticleUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *ArticleUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (auo *ArticleUpdateOne) sqlSave(ctx context.Context) (_node *Article, err error) {
	_spec := sqlgraph.NewUpdateSpec(article.Table, article.Columns, sqlgraph.NewFieldSpec(article.FieldID, field.TypeString))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Article.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, article.FieldID)
		for _, f := range fields {
			if !article.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != article.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.TitleChinese(); ok {
		_spec.SetField(article.FieldTitleChinese, field.TypeString, value)
	}
	if value, ok := auo.mutation.TitleEnglish(); ok {
		_spec.SetField(article.FieldTitleEnglish, field.TypeString, value)
	}
	if value, ok := auo.mutation.Author(); ok {
		_spec.SetField(article.FieldAuthor, field.TypeJSON, value)
	}
	if value, ok := auo.mutation.AppendedAuthor(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, article.FieldAuthor, value)
		})
	}
	if value, ok := auo.mutation.HTMLChinese(); ok {
		_spec.SetField(article.FieldHTMLChinese, field.TypeString, value)
	}
	if value, ok := auo.mutation.HTMLEnglish(); ok {
		_spec.SetField(article.FieldHTMLEnglish, field.TypeString, value)
	}
	if value, ok := auo.mutation.TextChinese(); ok {
		_spec.SetField(article.FieldTextChinese, field.TypeString, value)
	}
	if value, ok := auo.mutation.TextEnglish(); ok {
		_spec.SetField(article.FieldTextEnglish, field.TypeString, value)
	}
	if value, ok := auo.mutation.Images(); ok {
		_spec.SetField(article.FieldImages, field.TypeJSON, value)
	}
	if value, ok := auo.mutation.AppendedImages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, article.FieldImages, value)
		})
	}
	if value, ok := auo.mutation.WeakProcessed(); ok {
		_spec.SetField(article.FieldWeakProcessed, field.TypeBool, value)
	}
	if value, ok := auo.mutation.WeakRelated(); ok {
		_spec.SetField(article.FieldWeakRelated, field.TypeBool, value)
	}
	if value, ok := auo.mutation.WeakKeywords(); ok {
		_spec.SetField(article.FieldWeakKeywords, field.TypeJSON, value)
	}
	if value, ok := auo.mutation.AppendedWeakKeywords(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, article.FieldWeakKeywords, value)
		})
	}
	if value, ok := auo.mutation.StrongProcessed(); ok {
		_spec.SetField(article.FieldStrongProcessed, field.TypeBool, value)
	}
	if value, ok := auo.mutation.StrongRelated(); ok {
		_spec.SetField(article.FieldStrongRelated, field.TypeBool, value)
	}
	if value, ok := auo.mutation.StrongKeyword(); ok {
		_spec.SetField(article.FieldStrongKeyword, field.TypeJSON, value)
	}
	if auo.mutation.StrongKeywordCleared() {
		_spec.ClearField(article.FieldStrongKeyword, field.TypeJSON)
	}
	if value, ok := auo.mutation.StrongRelatedCategory(); ok {
		_spec.SetField(article.FieldStrongRelatedCategory, field.TypeString, value)
	}
	if value, ok := auo.mutation.SummaryChinese(); ok {
		_spec.SetField(article.FieldSummaryChinese, field.TypeString, value)
	}
	if value, ok := auo.mutation.ImageUploaded(); ok {
		_spec.SetField(article.FieldImageUploaded, field.TypeBool, value)
	}
	_node = &Article{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{article.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
