// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/wolodata/schema/ent/article"
)

// ArticleCreate is the builder for creating a Article entity.
type ArticleCreate struct {
	config
	mutation *ArticleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOriginShortID sets the "origin_short_id" field.
func (ac *ArticleCreate) SetOriginShortID(s string) *ArticleCreate {
	ac.mutation.SetOriginShortID(s)
	return ac
}

// SetIsChinese sets the "is_chinese" field.
func (ac *ArticleCreate) SetIsChinese(b bool) *ArticleCreate {
	ac.mutation.SetIsChinese(b)
	return ac
}

// SetNillableIsChinese sets the "is_chinese" field if the given value is not nil.
func (ac *ArticleCreate) SetNillableIsChinese(b *bool) *ArticleCreate {
	if b != nil {
		ac.SetIsChinese(*b)
	}
	return ac
}

// SetOriginType sets the "origin_type" field.
func (ac *ArticleCreate) SetOriginType(s string) *ArticleCreate {
	ac.mutation.SetOriginType(s)
	return ac
}

// SetURL sets the "url" field.
func (ac *ArticleCreate) SetURL(s string) *ArticleCreate {
	ac.mutation.SetURL(s)
	return ac
}

// SetTitleChinese sets the "title_chinese" field.
func (ac *ArticleCreate) SetTitleChinese(s string) *ArticleCreate {
	ac.mutation.SetTitleChinese(s)
	return ac
}

// SetNillableTitleChinese sets the "title_chinese" field if the given value is not nil.
func (ac *ArticleCreate) SetNillableTitleChinese(s *string) *ArticleCreate {
	if s != nil {
		ac.SetTitleChinese(*s)
	}
	return ac
}

// SetTitleEnglish sets the "title_english" field.
func (ac *ArticleCreate) SetTitleEnglish(s string) *ArticleCreate {
	ac.mutation.SetTitleEnglish(s)
	return ac
}

// SetNillableTitleEnglish sets the "title_english" field if the given value is not nil.
func (ac *ArticleCreate) SetNillableTitleEnglish(s *string) *ArticleCreate {
	if s != nil {
		ac.SetTitleEnglish(*s)
	}
	return ac
}

// SetAuthor sets the "author" field.
func (ac *ArticleCreate) SetAuthor(s string) *ArticleCreate {
	ac.mutation.SetAuthor(s)
	return ac
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (ac *ArticleCreate) SetNillableAuthor(s *string) *ArticleCreate {
	if s != nil {
		ac.SetAuthor(*s)
	}
	return ac
}

// SetTags sets the "tags" field.
func (ac *ArticleCreate) SetTags(s []string) *ArticleCreate {
	ac.mutation.SetTags(s)
	return ac
}

// SetPublishedAt sets the "published_at" field.
func (ac *ArticleCreate) SetPublishedAt(t time.Time) *ArticleCreate {
	ac.mutation.SetPublishedAt(t)
	return ac
}

// SetHTMLChinese sets the "html_chinese" field.
func (ac *ArticleCreate) SetHTMLChinese(s string) *ArticleCreate {
	ac.mutation.SetHTMLChinese(s)
	return ac
}

// SetNillableHTMLChinese sets the "html_chinese" field if the given value is not nil.
func (ac *ArticleCreate) SetNillableHTMLChinese(s *string) *ArticleCreate {
	if s != nil {
		ac.SetHTMLChinese(*s)
	}
	return ac
}

// SetHTMLEnglish sets the "html_english" field.
func (ac *ArticleCreate) SetHTMLEnglish(s string) *ArticleCreate {
	ac.mutation.SetHTMLEnglish(s)
	return ac
}

// SetNillableHTMLEnglish sets the "html_english" field if the given value is not nil.
func (ac *ArticleCreate) SetNillableHTMLEnglish(s *string) *ArticleCreate {
	if s != nil {
		ac.SetHTMLEnglish(*s)
	}
	return ac
}

// SetTextChinese sets the "text_chinese" field.
func (ac *ArticleCreate) SetTextChinese(s string) *ArticleCreate {
	ac.mutation.SetTextChinese(s)
	return ac
}

// SetNillableTextChinese sets the "text_chinese" field if the given value is not nil.
func (ac *ArticleCreate) SetNillableTextChinese(s *string) *ArticleCreate {
	if s != nil {
		ac.SetTextChinese(*s)
	}
	return ac
}

// SetTextEnglish sets the "text_english" field.
func (ac *ArticleCreate) SetTextEnglish(s string) *ArticleCreate {
	ac.mutation.SetTextEnglish(s)
	return ac
}

// SetNillableTextEnglish sets the "text_english" field if the given value is not nil.
func (ac *ArticleCreate) SetNillableTextEnglish(s *string) *ArticleCreate {
	if s != nil {
		ac.SetTextEnglish(*s)
	}
	return ac
}

// SetCrawledAt sets the "crawled_at" field.
func (ac *ArticleCreate) SetCrawledAt(t time.Time) *ArticleCreate {
	ac.mutation.SetCrawledAt(t)
	return ac
}

// SetNillableCrawledAt sets the "crawled_at" field if the given value is not nil.
func (ac *ArticleCreate) SetNillableCrawledAt(t *time.Time) *ArticleCreate {
	if t != nil {
		ac.SetCrawledAt(*t)
	}
	return ac
}

// SetSummaryChinese sets the "summary_chinese" field.
func (ac *ArticleCreate) SetSummaryChinese(s string) *ArticleCreate {
	ac.mutation.SetSummaryChinese(s)
	return ac
}

// SetNillableSummaryChinese sets the "summary_chinese" field if the given value is not nil.
func (ac *ArticleCreate) SetNillableSummaryChinese(s *string) *ArticleCreate {
	if s != nil {
		ac.SetSummaryChinese(*s)
	}
	return ac
}

// SetCategory sets the "category" field.
func (ac *ArticleCreate) SetCategory(s string) *ArticleCreate {
	ac.mutation.SetCategory(s)
	return ac
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (ac *ArticleCreate) SetNillableCategory(s *string) *ArticleCreate {
	if s != nil {
		ac.SetCategory(*s)
	}
	return ac
}

// SetID sets the "id" field.
func (ac *ArticleCreate) SetID(i int32) *ArticleCreate {
	ac.mutation.SetID(i)
	return ac
}

// Mutation returns the ArticleMutation object of the builder.
func (ac *ArticleCreate) Mutation() *ArticleMutation {
	return ac.mutation
}

// Save creates the Article in the database.
func (ac *ArticleCreate) Save(ctx context.Context) (*Article, error) {
	ac.defaults()
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *ArticleCreate) SaveX(ctx context.Context) *Article {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *ArticleCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *ArticleCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *ArticleCreate) defaults() {
	if _, ok := ac.mutation.IsChinese(); !ok {
		v := article.DefaultIsChinese
		ac.mutation.SetIsChinese(v)
	}
	if _, ok := ac.mutation.TitleChinese(); !ok {
		v := article.DefaultTitleChinese
		ac.mutation.SetTitleChinese(v)
	}
	if _, ok := ac.mutation.TitleEnglish(); !ok {
		v := article.DefaultTitleEnglish
		ac.mutation.SetTitleEnglish(v)
	}
	if _, ok := ac.mutation.Author(); !ok {
		v := article.DefaultAuthor
		ac.mutation.SetAuthor(v)
	}
	if _, ok := ac.mutation.Tags(); !ok {
		v := article.DefaultTags
		ac.mutation.SetTags(v)
	}
	if _, ok := ac.mutation.HTMLChinese(); !ok {
		v := article.DefaultHTMLChinese
		ac.mutation.SetHTMLChinese(v)
	}
	if _, ok := ac.mutation.HTMLEnglish(); !ok {
		v := article.DefaultHTMLEnglish
		ac.mutation.SetHTMLEnglish(v)
	}
	if _, ok := ac.mutation.TextChinese(); !ok {
		v := article.DefaultTextChinese
		ac.mutation.SetTextChinese(v)
	}
	if _, ok := ac.mutation.TextEnglish(); !ok {
		v := article.DefaultTextEnglish
		ac.mutation.SetTextEnglish(v)
	}
	if _, ok := ac.mutation.CrawledAt(); !ok {
		v := article.DefaultCrawledAt()
		ac.mutation.SetCrawledAt(v)
	}
	if _, ok := ac.mutation.SummaryChinese(); !ok {
		v := article.DefaultSummaryChinese
		ac.mutation.SetSummaryChinese(v)
	}
	if _, ok := ac.mutation.Category(); !ok {
		v := article.DefaultCategory
		ac.mutation.SetCategory(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *ArticleCreate) check() error {
	if _, ok := ac.mutation.OriginShortID(); !ok {
		return &ValidationError{Name: "origin_short_id", err: errors.New(`ent: missing required field "Article.origin_short_id"`)}
	}
	if v, ok := ac.mutation.OriginShortID(); ok {
		if err := article.OriginShortIDValidator(v); err != nil {
			return &ValidationError{Name: "origin_short_id", err: fmt.Errorf(`ent: validator failed for field "Article.origin_short_id": %w`, err)}
		}
	}
	if _, ok := ac.mutation.IsChinese(); !ok {
		return &ValidationError{Name: "is_chinese", err: errors.New(`ent: missing required field "Article.is_chinese"`)}
	}
	if _, ok := ac.mutation.OriginType(); !ok {
		return &ValidationError{Name: "origin_type", err: errors.New(`ent: missing required field "Article.origin_type"`)}
	}
	if _, ok := ac.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Article.url"`)}
	}
	if v, ok := ac.mutation.URL(); ok {
		if err := article.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Article.url": %w`, err)}
		}
	}
	if _, ok := ac.mutation.TitleChinese(); !ok {
		return &ValidationError{Name: "title_chinese", err: errors.New(`ent: missing required field "Article.title_chinese"`)}
	}
	if _, ok := ac.mutation.TitleEnglish(); !ok {
		return &ValidationError{Name: "title_english", err: errors.New(`ent: missing required field "Article.title_english"`)}
	}
	if _, ok := ac.mutation.Author(); !ok {
		return &ValidationError{Name: "author", err: errors.New(`ent: missing required field "Article.author"`)}
	}
	if _, ok := ac.mutation.Tags(); !ok {
		return &ValidationError{Name: "tags", err: errors.New(`ent: missing required field "Article.tags"`)}
	}
	if _, ok := ac.mutation.PublishedAt(); !ok {
		return &ValidationError{Name: "published_at", err: errors.New(`ent: missing required field "Article.published_at"`)}
	}
	if _, ok := ac.mutation.HTMLChinese(); !ok {
		return &ValidationError{Name: "html_chinese", err: errors.New(`ent: missing required field "Article.html_chinese"`)}
	}
	if _, ok := ac.mutation.HTMLEnglish(); !ok {
		return &ValidationError{Name: "html_english", err: errors.New(`ent: missing required field "Article.html_english"`)}
	}
	if _, ok := ac.mutation.TextChinese(); !ok {
		return &ValidationError{Name: "text_chinese", err: errors.New(`ent: missing required field "Article.text_chinese"`)}
	}
	if _, ok := ac.mutation.TextEnglish(); !ok {
		return &ValidationError{Name: "text_english", err: errors.New(`ent: missing required field "Article.text_english"`)}
	}
	if _, ok := ac.mutation.CrawledAt(); !ok {
		return &ValidationError{Name: "crawled_at", err: errors.New(`ent: missing required field "Article.crawled_at"`)}
	}
	if _, ok := ac.mutation.SummaryChinese(); !ok {
		return &ValidationError{Name: "summary_chinese", err: errors.New(`ent: missing required field "Article.summary_chinese"`)}
	}
	if _, ok := ac.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Article.category"`)}
	}
	return nil
}

func (ac *ArticleCreate) sqlSave(ctx context.Context) (*Article, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int32(id)
	}
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *ArticleCreate) createSpec() (*Article, *sqlgraph.CreateSpec) {
	var (
		_node = &Article{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(article.Table, sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt32))
	)
	_spec.OnConflict = ac.conflict
	if id, ok := ac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ac.mutation.OriginShortID(); ok {
		_spec.SetField(article.FieldOriginShortID, field.TypeString, value)
		_node.OriginShortID = value
	}
	if value, ok := ac.mutation.IsChinese(); ok {
		_spec.SetField(article.FieldIsChinese, field.TypeBool, value)
		_node.IsChinese = value
	}
	if value, ok := ac.mutation.OriginType(); ok {
		_spec.SetField(article.FieldOriginType, field.TypeString, value)
		_node.OriginType = value
	}
	if value, ok := ac.mutation.URL(); ok {
		_spec.SetField(article.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := ac.mutation.TitleChinese(); ok {
		_spec.SetField(article.FieldTitleChinese, field.TypeString, value)
		_node.TitleChinese = value
	}
	if value, ok := ac.mutation.TitleEnglish(); ok {
		_spec.SetField(article.FieldTitleEnglish, field.TypeString, value)
		_node.TitleEnglish = value
	}
	if value, ok := ac.mutation.Author(); ok {
		_spec.SetField(article.FieldAuthor, field.TypeString, value)
		_node.Author = value
	}
	if value, ok := ac.mutation.Tags(); ok {
		_spec.SetField(article.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := ac.mutation.PublishedAt(); ok {
		_spec.SetField(article.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = value
	}
	if value, ok := ac.mutation.HTMLChinese(); ok {
		_spec.SetField(article.FieldHTMLChinese, field.TypeString, value)
		_node.HTMLChinese = value
	}
	if value, ok := ac.mutation.HTMLEnglish(); ok {
		_spec.SetField(article.FieldHTMLEnglish, field.TypeString, value)
		_node.HTMLEnglish = value
	}
	if value, ok := ac.mutation.TextChinese(); ok {
		_spec.SetField(article.FieldTextChinese, field.TypeString, value)
		_node.TextChinese = value
	}
	if value, ok := ac.mutation.TextEnglish(); ok {
		_spec.SetField(article.FieldTextEnglish, field.TypeString, value)
		_node.TextEnglish = value
	}
	if value, ok := ac.mutation.CrawledAt(); ok {
		_spec.SetField(article.FieldCrawledAt, field.TypeTime, value)
		_node.CrawledAt = value
	}
	if value, ok := ac.mutation.SummaryChinese(); ok {
		_spec.SetField(article.FieldSummaryChinese, field.TypeString, value)
		_node.SummaryChinese = value
	}
	if value, ok := ac.mutation.Category(); ok {
		_spec.SetField(article.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Article.Create().
//		SetOriginShortID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ArticleUpsert) {
//			SetOriginShortID(v+v).
//		}).
//		Exec(ctx)
func (ac *ArticleCreate) OnConflict(opts ...sql.ConflictOption) *ArticleUpsertOne {
	ac.conflict = opts
	return &ArticleUpsertOne{
		create: ac,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Article.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ac *ArticleCreate) OnConflictColumns(columns ...string) *ArticleUpsertOne {
	ac.conflict = append(ac.conflict, sql.ConflictColumns(columns...))
	return &ArticleUpsertOne{
		create: ac,
	}
}

type (
	// ArticleUpsertOne is the builder for "upsert"-ing
	//  one Article node.
	ArticleUpsertOne struct {
		create *ArticleCreate
	}

	// ArticleUpsert is the "OnConflict" setter.
	ArticleUpsert struct {
		*sql.UpdateSet
	}
)

// SetTitleChinese sets the "title_chinese" field.
func (u *ArticleUpsert) SetTitleChinese(v string) *ArticleUpsert {
	u.Set(article.FieldTitleChinese, v)
	return u
}

// UpdateTitleChinese sets the "title_chinese" field to the value that was provided on create.
func (u *ArticleUpsert) UpdateTitleChinese() *ArticleUpsert {
	u.SetExcluded(article.FieldTitleChinese)
	return u
}

// SetTitleEnglish sets the "title_english" field.
func (u *ArticleUpsert) SetTitleEnglish(v string) *ArticleUpsert {
	u.Set(article.FieldTitleEnglish, v)
	return u
}

// UpdateTitleEnglish sets the "title_english" field to the value that was provided on create.
func (u *ArticleUpsert) UpdateTitleEnglish() *ArticleUpsert {
	u.SetExcluded(article.FieldTitleEnglish)
	return u
}

// SetAuthor sets the "author" field.
func (u *ArticleUpsert) SetAuthor(v string) *ArticleUpsert {
	u.Set(article.FieldAuthor, v)
	return u
}

// UpdateAuthor sets the "author" field to the value that was provided on create.
func (u *ArticleUpsert) UpdateAuthor() *ArticleUpsert {
	u.SetExcluded(article.FieldAuthor)
	return u
}

// SetTags sets the "tags" field.
func (u *ArticleUpsert) SetTags(v []string) *ArticleUpsert {
	u.Set(article.FieldTags, v)
	return u
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *ArticleUpsert) UpdateTags() *ArticleUpsert {
	u.SetExcluded(article.FieldTags)
	return u
}

// SetHTMLChinese sets the "html_chinese" field.
func (u *ArticleUpsert) SetHTMLChinese(v string) *ArticleUpsert {
	u.Set(article.FieldHTMLChinese, v)
	return u
}

// UpdateHTMLChinese sets the "html_chinese" field to the value that was provided on create.
func (u *ArticleUpsert) UpdateHTMLChinese() *ArticleUpsert {
	u.SetExcluded(article.FieldHTMLChinese)
	return u
}

// SetHTMLEnglish sets the "html_english" field.
func (u *ArticleUpsert) SetHTMLEnglish(v string) *ArticleUpsert {
	u.Set(article.FieldHTMLEnglish, v)
	return u
}

// UpdateHTMLEnglish sets the "html_english" field to the value that was provided on create.
func (u *ArticleUpsert) UpdateHTMLEnglish() *ArticleUpsert {
	u.SetExcluded(article.FieldHTMLEnglish)
	return u
}

// SetTextChinese sets the "text_chinese" field.
func (u *ArticleUpsert) SetTextChinese(v string) *ArticleUpsert {
	u.Set(article.FieldTextChinese, v)
	return u
}

// UpdateTextChinese sets the "text_chinese" field to the value that was provided on create.
func (u *ArticleUpsert) UpdateTextChinese() *ArticleUpsert {
	u.SetExcluded(article.FieldTextChinese)
	return u
}

// SetTextEnglish sets the "text_english" field.
func (u *ArticleUpsert) SetTextEnglish(v string) *ArticleUpsert {
	u.Set(article.FieldTextEnglish, v)
	return u
}

// UpdateTextEnglish sets the "text_english" field to the value that was provided on create.
func (u *ArticleUpsert) UpdateTextEnglish() *ArticleUpsert {
	u.SetExcluded(article.FieldTextEnglish)
	return u
}

// SetSummaryChinese sets the "summary_chinese" field.
func (u *ArticleUpsert) SetSummaryChinese(v string) *ArticleUpsert {
	u.Set(article.FieldSummaryChinese, v)
	return u
}

// UpdateSummaryChinese sets the "summary_chinese" field to the value that was provided on create.
func (u *ArticleUpsert) UpdateSummaryChinese() *ArticleUpsert {
	u.SetExcluded(article.FieldSummaryChinese)
	return u
}

// SetCategory sets the "category" field.
func (u *ArticleUpsert) SetCategory(v string) *ArticleUpsert {
	u.Set(article.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *ArticleUpsert) UpdateCategory() *ArticleUpsert {
	u.SetExcluded(article.FieldCategory)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Article.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(article.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ArticleUpsertOne) UpdateNewValues() *ArticleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(article.FieldID)
		}
		if _, exists := u.create.mutation.OriginShortID(); exists {
			s.SetIgnore(article.FieldOriginShortID)
		}
		if _, exists := u.create.mutation.IsChinese(); exists {
			s.SetIgnore(article.FieldIsChinese)
		}
		if _, exists := u.create.mutation.OriginType(); exists {
			s.SetIgnore(article.FieldOriginType)
		}
		if _, exists := u.create.mutation.URL(); exists {
			s.SetIgnore(article.FieldURL)
		}
		if _, exists := u.create.mutation.PublishedAt(); exists {
			s.SetIgnore(article.FieldPublishedAt)
		}
		if _, exists := u.create.mutation.CrawledAt(); exists {
			s.SetIgnore(article.FieldCrawledAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Article.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ArticleUpsertOne) Ignore() *ArticleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ArticleUpsertOne) DoNothing() *ArticleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ArticleCreate.OnConflict
// documentation for more info.
func (u *ArticleUpsertOne) Update(set func(*ArticleUpsert)) *ArticleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ArticleUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitleChinese sets the "title_chinese" field.
func (u *ArticleUpsertOne) SetTitleChinese(v string) *ArticleUpsertOne {
	return u.Update(func(s *ArticleUpsert) {
		s.SetTitleChinese(v)
	})
}

// UpdateTitleChinese sets the "title_chinese" field to the value that was provided on create.
func (u *ArticleUpsertOne) UpdateTitleChinese() *ArticleUpsertOne {
	return u.Update(func(s *ArticleUpsert) {
		s.UpdateTitleChinese()
	})
}

// SetTitleEnglish sets the "title_english" field.
func (u *ArticleUpsertOne) SetTitleEnglish(v string) *ArticleUpsertOne {
	return u.Update(func(s *ArticleUpsert) {
		s.SetTitleEnglish(v)
	})
}

// UpdateTitleEnglish sets the "title_english" field to the value that was provided on create.
func (u *ArticleUpsertOne) UpdateTitleEnglish() *ArticleUpsertOne {
	return u.Update(func(s *ArticleUpsert) {
		s.UpdateTitleEnglish()
	})
}

// SetAuthor sets the "author" field.
func (u *ArticleUpsertOne) SetAuthor(v string) *ArticleUpsertOne {
	return u.Update(func(s *ArticleUpsert) {
		s.SetAuthor(v)
	})
}

// UpdateAuthor sets the "author" field to the value that was provided on create.
func (u *ArticleUpsertOne) UpdateAuthor() *ArticleUpsertOne {
	return u.Update(func(s *ArticleUpsert) {
		s.UpdateAuthor()
	})
}

// SetTags sets the "tags" field.
func (u *ArticleUpsertOne) SetTags(v []string) *ArticleUpsertOne {
	return u.Update(func(s *ArticleUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *ArticleUpsertOne) UpdateTags() *ArticleUpsertOne {
	return u.Update(func(s *ArticleUpsert) {
		s.UpdateTags()
	})
}

// SetHTMLChinese sets the "html_chinese" field.
func (u *ArticleUpsertOne) SetHTMLChinese(v string) *ArticleUpsertOne {
	return u.Update(func(s *ArticleUpsert) {
		s.SetHTMLChinese(v)
	})
}

// UpdateHTMLChinese sets the "html_chinese" field to the value that was provided on create.
func (u *ArticleUpsertOne) UpdateHTMLChinese() *ArticleUpsertOne {
	return u.Update(func(s *ArticleUpsert) {
		s.UpdateHTMLChinese()
	})
}

// SetHTMLEnglish sets the "html_english" field.
func (u *ArticleUpsertOne) SetHTMLEnglish(v string) *ArticleUpsertOne {
	return u.Update(func(s *ArticleUpsert) {
		s.SetHTMLEnglish(v)
	})
}

// UpdateHTMLEnglish sets the "html_english" field to the value that was provided on create.
func (u *ArticleUpsertOne) UpdateHTMLEnglish() *ArticleUpsertOne {
	return u.Update(func(s *ArticleUpsert) {
		s.UpdateHTMLEnglish()
	})
}

// SetTextChinese sets the "text_chinese" field.
func (u *ArticleUpsertOne) SetTextChinese(v string) *ArticleUpsertOne {
	return u.Update(func(s *ArticleUpsert) {
		s.SetTextChinese(v)
	})
}

// UpdateTextChinese sets the "text_chinese" field to the value that was provided on create.
func (u *ArticleUpsertOne) UpdateTextChinese() *ArticleUpsertOne {
	return u.Update(func(s *ArticleUpsert) {
		s.UpdateTextChinese()
	})
}

// SetTextEnglish sets the "text_english" field.
func (u *ArticleUpsertOne) SetTextEnglish(v string) *ArticleUpsertOne {
	return u.Update(func(s *ArticleUpsert) {
		s.SetTextEnglish(v)
	})
}

// UpdateTextEnglish sets the "text_english" field to the value that was provided on create.
func (u *ArticleUpsertOne) UpdateTextEnglish() *ArticleUpsertOne {
	return u.Update(func(s *ArticleUpsert) {
		s.UpdateTextEnglish()
	})
}

// SetSummaryChinese sets the "summary_chinese" field.
func (u *ArticleUpsertOne) SetSummaryChinese(v string) *ArticleUpsertOne {
	return u.Update(func(s *ArticleUpsert) {
		s.SetSummaryChinese(v)
	})
}

// UpdateSummaryChinese sets the "summary_chinese" field to the value that was provided on create.
func (u *ArticleUpsertOne) UpdateSummaryChinese() *ArticleUpsertOne {
	return u.Update(func(s *ArticleUpsert) {
		s.UpdateSummaryChinese()
	})
}

// SetCategory sets the "category" field.
func (u *ArticleUpsertOne) SetCategory(v string) *ArticleUpsertOne {
	return u.Update(func(s *ArticleUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *ArticleUpsertOne) UpdateCategory() *ArticleUpsertOne {
	return u.Update(func(s *ArticleUpsert) {
		s.UpdateCategory()
	})
}

// Exec executes the query.
func (u *ArticleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ArticleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ArticleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ArticleUpsertOne) ID(ctx context.Context) (id int32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ArticleUpsertOne) IDX(ctx context.Context) int32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ArticleCreateBulk is the builder for creating many Article entities in bulk.
type ArticleCreateBulk struct {
	config
	err      error
	builders []*ArticleCreate
	conflict []sql.ConflictOption
}

// Save creates the Article entities in the database.
func (acb *ArticleCreateBulk) Save(ctx context.Context) ([]*Article, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Article, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ArticleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = acb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *ArticleCreateBulk) SaveX(ctx context.Context) []*Article {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *ArticleCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *ArticleCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Article.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ArticleUpsert) {
//			SetOriginShortID(v+v).
//		}).
//		Exec(ctx)
func (acb *ArticleCreateBulk) OnConflict(opts ...sql.ConflictOption) *ArticleUpsertBulk {
	acb.conflict = opts
	return &ArticleUpsertBulk{
		create: acb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Article.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (acb *ArticleCreateBulk) OnConflictColumns(columns ...string) *ArticleUpsertBulk {
	acb.conflict = append(acb.conflict, sql.ConflictColumns(columns...))
	return &ArticleUpsertBulk{
		create: acb,
	}
}

// ArticleUpsertBulk is the builder for "upsert"-ing
// a bulk of Article nodes.
type ArticleUpsertBulk struct {
	create *ArticleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Article.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(article.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ArticleUpsertBulk) UpdateNewValues() *ArticleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(article.FieldID)
			}
			if _, exists := b.mutation.OriginShortID(); exists {
				s.SetIgnore(article.FieldOriginShortID)
			}
			if _, exists := b.mutation.IsChinese(); exists {
				s.SetIgnore(article.FieldIsChinese)
			}
			if _, exists := b.mutation.OriginType(); exists {
				s.SetIgnore(article.FieldOriginType)
			}
			if _, exists := b.mutation.URL(); exists {
				s.SetIgnore(article.FieldURL)
			}
			if _, exists := b.mutation.PublishedAt(); exists {
				s.SetIgnore(article.FieldPublishedAt)
			}
			if _, exists := b.mutation.CrawledAt(); exists {
				s.SetIgnore(article.FieldCrawledAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Article.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ArticleUpsertBulk) Ignore() *ArticleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ArticleUpsertBulk) DoNothing() *ArticleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ArticleCreateBulk.OnConflict
// documentation for more info.
func (u *ArticleUpsertBulk) Update(set func(*ArticleUpsert)) *ArticleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ArticleUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitleChinese sets the "title_chinese" field.
func (u *ArticleUpsertBulk) SetTitleChinese(v string) *ArticleUpsertBulk {
	return u.Update(func(s *ArticleUpsert) {
		s.SetTitleChinese(v)
	})
}

// UpdateTitleChinese sets the "title_chinese" field to the value that was provided on create.
func (u *ArticleUpsertBulk) UpdateTitleChinese() *ArticleUpsertBulk {
	return u.Update(func(s *ArticleUpsert) {
		s.UpdateTitleChinese()
	})
}

// SetTitleEnglish sets the "title_english" field.
func (u *ArticleUpsertBulk) SetTitleEnglish(v string) *ArticleUpsertBulk {
	return u.Update(func(s *ArticleUpsert) {
		s.SetTitleEnglish(v)
	})
}

// UpdateTitleEnglish sets the "title_english" field to the value that was provided on create.
func (u *ArticleUpsertBulk) UpdateTitleEnglish() *ArticleUpsertBulk {
	return u.Update(func(s *ArticleUpsert) {
		s.UpdateTitleEnglish()
	})
}

// SetAuthor sets the "author" field.
func (u *ArticleUpsertBulk) SetAuthor(v string) *ArticleUpsertBulk {
	return u.Update(func(s *ArticleUpsert) {
		s.SetAuthor(v)
	})
}

// UpdateAuthor sets the "author" field to the value that was provided on create.
func (u *ArticleUpsertBulk) UpdateAuthor() *ArticleUpsertBulk {
	return u.Update(func(s *ArticleUpsert) {
		s.UpdateAuthor()
	})
}

// SetTags sets the "tags" field.
func (u *ArticleUpsertBulk) SetTags(v []string) *ArticleUpsertBulk {
	return u.Update(func(s *ArticleUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *ArticleUpsertBulk) UpdateTags() *ArticleUpsertBulk {
	return u.Update(func(s *ArticleUpsert) {
		s.UpdateTags()
	})
}

// SetHTMLChinese sets the "html_chinese" field.
func (u *ArticleUpsertBulk) SetHTMLChinese(v string) *ArticleUpsertBulk {
	return u.Update(func(s *ArticleUpsert) {
		s.SetHTMLChinese(v)
	})
}

// UpdateHTMLChinese sets the "html_chinese" field to the value that was provided on create.
func (u *ArticleUpsertBulk) UpdateHTMLChinese() *ArticleUpsertBulk {
	return u.Update(func(s *ArticleUpsert) {
		s.UpdateHTMLChinese()
	})
}

// SetHTMLEnglish sets the "html_english" field.
func (u *ArticleUpsertBulk) SetHTMLEnglish(v string) *ArticleUpsertBulk {
	return u.Update(func(s *ArticleUpsert) {
		s.SetHTMLEnglish(v)
	})
}

// UpdateHTMLEnglish sets the "html_english" field to the value that was provided on create.
func (u *ArticleUpsertBulk) UpdateHTMLEnglish() *ArticleUpsertBulk {
	return u.Update(func(s *ArticleUpsert) {
		s.UpdateHTMLEnglish()
	})
}

// SetTextChinese sets the "text_chinese" field.
func (u *ArticleUpsertBulk) SetTextChinese(v string) *ArticleUpsertBulk {
	return u.Update(func(s *ArticleUpsert) {
		s.SetTextChinese(v)
	})
}

// UpdateTextChinese sets the "text_chinese" field to the value that was provided on create.
func (u *ArticleUpsertBulk) UpdateTextChinese() *ArticleUpsertBulk {
	return u.Update(func(s *ArticleUpsert) {
		s.UpdateTextChinese()
	})
}

// SetTextEnglish sets the "text_english" field.
func (u *ArticleUpsertBulk) SetTextEnglish(v string) *ArticleUpsertBulk {
	return u.Update(func(s *ArticleUpsert) {
		s.SetTextEnglish(v)
	})
}

// UpdateTextEnglish sets the "text_english" field to the value that was provided on create.
func (u *ArticleUpsertBulk) UpdateTextEnglish() *ArticleUpsertBulk {
	return u.Update(func(s *ArticleUpsert) {
		s.UpdateTextEnglish()
	})
}

// SetSummaryChinese sets the "summary_chinese" field.
func (u *ArticleUpsertBulk) SetSummaryChinese(v string) *ArticleUpsertBulk {
	return u.Update(func(s *ArticleUpsert) {
		s.SetSummaryChinese(v)
	})
}

// UpdateSummaryChinese sets the "summary_chinese" field to the value that was provided on create.
func (u *ArticleUpsertBulk) UpdateSummaryChinese() *ArticleUpsertBulk {
	return u.Update(func(s *ArticleUpsert) {
		s.UpdateSummaryChinese()
	})
}

// SetCategory sets the "category" field.
func (u *ArticleUpsertBulk) SetCategory(v string) *ArticleUpsertBulk {
	return u.Update(func(s *ArticleUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *ArticleUpsertBulk) UpdateCategory() *ArticleUpsertBulk {
	return u.Update(func(s *ArticleUpsert) {
		s.UpdateCategory()
	})
}

// Exec executes the query.
func (u *ArticleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ArticleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ArticleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ArticleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
