// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/wolodata/schema/ent/systemconfig"
)

// SystemConfig is the model entity for the SystemConfig schema.
type SystemConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// APIModel holds the value of the "api_model" field.
	APIModel string `json:"api_model,omitempty"`
	// APIURL holds the value of the "api_url" field.
	APIURL string `json:"api_url,omitempty"`
	// APIKey holds the value of the "api_key" field.
	APIKey string `json:"api_key,omitempty"`
	// PromptSystem holds the value of the "prompt_system" field.
	PromptSystem string `json:"prompt_system,omitempty"`
	// PromptUser holds the value of the "prompt_user" field.
	PromptUser   string `json:"prompt_user,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SystemConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case systemconfig.FieldID, systemconfig.FieldName, systemconfig.FieldDescription, systemconfig.FieldAPIModel, systemconfig.FieldAPIURL, systemconfig.FieldAPIKey, systemconfig.FieldPromptSystem, systemconfig.FieldPromptUser:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SystemConfig fields.
func (sc *SystemConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case systemconfig.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				sc.ID = value.String
			}
		case systemconfig.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				sc.Name = value.String
			}
		case systemconfig.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				sc.Description = value.String
			}
		case systemconfig.FieldAPIModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_model", values[i])
			} else if value.Valid {
				sc.APIModel = value.String
			}
		case systemconfig.FieldAPIURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_url", values[i])
			} else if value.Valid {
				sc.APIURL = value.String
			}
		case systemconfig.FieldAPIKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_key", values[i])
			} else if value.Valid {
				sc.APIKey = value.String
			}
		case systemconfig.FieldPromptSystem:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_system", values[i])
			} else if value.Valid {
				sc.PromptSystem = value.String
			}
		case systemconfig.FieldPromptUser:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_user", values[i])
			} else if value.Valid {
				sc.PromptUser = value.String
			}
		default:
			sc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SystemConfig.
// This includes values selected through modifiers, order, etc.
func (sc *SystemConfig) Value(name string) (ent.Value, error) {
	return sc.selectValues.Get(name)
}

// Update returns a builder for updating this SystemConfig.
// Note that you need to call SystemConfig.Unwrap() before calling this method if this SystemConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (sc *SystemConfig) Update() *SystemConfigUpdateOne {
	return NewSystemConfigClient(sc.config).UpdateOne(sc)
}

// Unwrap unwraps the SystemConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sc *SystemConfig) Unwrap() *SystemConfig {
	_tx, ok := sc.config.driver.(*txDriver)
	if !ok {
		panic("ent: SystemConfig is not a transactional entity")
	}
	sc.config.driver = _tx.drv
	return sc
}

// String implements the fmt.Stringer.
func (sc *SystemConfig) String() string {
	var builder strings.Builder
	builder.WriteString("SystemConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sc.ID))
	builder.WriteString("name=")
	builder.WriteString(sc.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(sc.Description)
	builder.WriteString(", ")
	builder.WriteString("api_model=")
	builder.WriteString(sc.APIModel)
	builder.WriteString(", ")
	builder.WriteString("api_url=")
	builder.WriteString(sc.APIURL)
	builder.WriteString(", ")
	builder.WriteString("api_key=")
	builder.WriteString(sc.APIKey)
	builder.WriteString(", ")
	builder.WriteString("prompt_system=")
	builder.WriteString(sc.PromptSystem)
	builder.WriteString(", ")
	builder.WriteString("prompt_user=")
	builder.WriteString(sc.PromptUser)
	builder.WriteByte(')')
	return builder.String()
}

// SystemConfigs is a parsable slice of SystemConfig.
type SystemConfigs []*SystemConfig
